### ISSUE TITLE
Weather not working

### ISSUE THREAD

**Issue by dpsewell** [BlythMeister/Fitbit-Overview-Face#104]
Hi, the weather isn't working on my versa 3 at times. When I try to update settings, it doesn't sync to the watch. Is anyone else having this issue? I've restated my watch twice as well.

**Comment by BlythMeister** [comment]
Are you using an iPhone?

**Comment by dpsewell** [comment]
Nope, android

**Comment by BlythMeister** [comment]
Have you enabled the location permission?

**Comment by dpsewell** [comment]
Yep! I sure did! It was working fine before I realized you had done these updates, so I added weather and it just gives me a tan rainbow with a bar next to it. Occasionally it'll work but now it's not at all and if I go into settings and change things, it won't update on my watch. Not sure what's going on.

**Comment by dpsewell** [comment]
It randomly started working again! 🤞🏼

**Comment by BlythMeister** [comment]
There is a new version that I've been working on which may improve things
It also includes a phone connection indicator which tells you if the watch is getting any information from the phone.

The biggest problem I have seen is the automated memory management on the phone will randomly stop the phone part from running and result in no messages passing between the phone and the watch (even though it's able to sync)

The only ways I've been able to get the watch to start talking again is to either open an app on the watch (like the alarms) and the close it.  This causes the Clockface to restart.
Or, if that doesn't work, open the settings on the phone and turn something off and then on again.
Or (the nuclear option) restart the phone.

**Comment by dpsewell** [comment]
Cheers!!!! I woke up and it was still working so hopefully it's fixed
itself. I appreciate you!

~Demi Pengelly Sewell

**Comment by dpsewell** [comment]
Update on weather. Been off and on all day. Not sure why it does this but
might just disable it, as kinda pointless if it doesn't work all the time.
Bummer.

~Demi Pengelly Sewell

**Comment by BlythMeister** [comment]
There is a fix on the way.
I've been using the pre-release that I'm waiting on Fitbit to approve and it seems a lot more stable.

**Comment by dpsewell** [comment]
Thank you!!!
