### ISSUE TITLE
Allow a way to toggle off new icons in top left

### ISSUE THREAD

**Issue by dml5064** [BlythMeister/Fitbit-Overview-Face#106]
They are cut off and I don't want them. 
![16624318852438751332467827307196](https://user-images.githubusercontent.com/63750464/188535398-65db14d5-b7e2-425a-98c2-6dbd57d49c7f.jpg)

**Comment by BlythMeister** [comment]
This is a bug that has been fixed in the next version.  I am awaiting Fitbit approval to release.

**Comment by dml5064** [comment]
Awesome thanks!

-
Dave Leone
