### ISSUE TITLE
Sense 2 

### ISSUE THREAD

**Issue by Snowman20001** [BlythMeister/Fitbit-Overview-Face#115]
Unable to install on sense 2 fitbit   any plans ?

**Comment by BlythMeister** [comment]
I would love to have Sense 2 and Versa 4 support but Fitbit are not allowing developers access to make faces for these devices

**Comment by drothenberger** [comment]
There are many third-party watch faces for the Sense 2. How are they being developed?

**Comment by BlythMeister** [comment]
Fitbit have converted some faces themselves.  But not open for developers.

There are numerous threads on their forums complaining since September.
