### ISSUE TITLE
Clock face doesn't show up

### ISSUE THREAD

**Issue by jcw349** [BlythMeister/Fitbit-Overview-Face#132]
Over the past month, this clock face keeps staying black. 

I had made sure my Fitbit still works. Can still use the Fitbit (swipe to other pages and Fitbit still works) and when switched to a different clock face, everything shows up. When I try to switch back to Overview clock face, it would be stuck forever and unable to reload the clock face. I had to uninstall entirely and reinstall for it to work again. 

This has happened multiple times already. When this happens it's after I charge my Fitbit.

Hope this gets fixed. I love this clock face. No other ones show all the stats this one does in such an organized way.

**Comment by BlythMeister** [comment]
This is a known issue and the fixes are currently with Fitbit to review (and have been for 2 weeks!)

Until Fitbit approve the release, i can't ship a fix. :(
There is the pre-release (link in readme) which has the latest build. - but this version may be less stable.
