### ISSUE TITLE
Switching fails or takes 20 minutes to more than 2 hours to complete

### ISSUE THREAD

**Issue by evilsplorp** [BlythMeister/Fitbit-Overview-Face#133]
Over the last month or so (I don't have an exact date), switching TO the Overview watch face from either the Fitbit app or the Sense (gen 1) fails. I end up with a black watch face. Initially, I thought the watch had died, but swiping shows the other screens normally. 

Within the app, I will sometimes get a modal:

Unable to install
Install failed, please try again later.

I will also occasionally get:

Continue installing?
Some applications did not finish installing.
Do you want to continue installing them now?
[Later] [Continue]

App Version is 1.16.5-366X366-6X

I have removed and reinstalled the watch face. If I leave the app / watch alone, it sometimes completes the installation with no further input. Sometimes, I cannot change to a visible watch face and have to restart the watch.

I really like the watch face and have used it for quite some time. If you need more information, let me know.

**Comment by BlythMeister** [comment]
This is a known issue.
The fix is on the pre-release already (see readme)

I am waiting on Fitbit to approve this (and have been for some time)
