### ISSUE TITLE
Photo background

### ISSUE THREAD

**Issue by BlythMeister** [BlythMeister/Fitbit-Overview-Face#54]
Allow a photo to be set as background rather than colour.

**Comment by cliang06948** [comment]
In the index.view, simply put  &lt;image href=&quot;.yourpic.png&quot; /&gt; after the line &lt;rect id=&quot;background&quot; /&gt; 
Of cousre, put yourpic.png (or jpg) in the resources folder

**Comment by BlythMeister** [comment]
The request was for a user choice of image for the background.

**Comment by BlythMeister** [comment]
Closing as not supported (for upload of image dynamically)
