### ISSUE TITLE
Create 5.0 version

### ISSUE THREAD

**Issue by BlythMeister** [BlythMeister/Fitbit-Overview-Face#55]
https://dev.fitbit.com/blog/2020-09-24-announcing-fitbit-os-sdk-5.0/

**Comment by TechFan7** [comment]
You wanting any team help with this?

**Comment by BlythMeister** [comment]
I'm not sure on the approach I want to take yet.

There are some breaking changes to the config I've been thinking of doing.

And since it seems SDK 5.0 will basically require a new version, new screen sizes etc and any existing installs will not get the SDK 5.0 versions it feels like a good time to do those changes too.

But would essentially mean there is a split in the codebase.

A watch face for 4.2 devices and one for 5.0 devices.

**Comment by TechFan7** [comment]
Yes, it looks like some pretty major changes needed. I have a Versa 3 arriving on Monday and my tweaked version of this watchface has been my primary on my Versa 2.  Glad to help if I can be of some use.

Sep 27, 2020 12:07:45 AM Chris Blyth <notifications@github.com>:
