### ISSUE TITLE
Sprite-Image as animated background not work

### ISSUE THREAD

**Issue by cliang06948** [BlythMeister/Fitbit-Overview-Face#56]
I tried to add the codes from https://dev.fitbit.com/build/guides/user-interface/svg-components/other/ to include a series of .png as animated clock face background but it doesn't work.  For adding a single image with &lt;image&gt; tag, this works. 
 
The same sprite-image codes are tried out in the sample clock project from studio.fitbit.com, they work.

Appreciate if any clues from the community.  Thanks

**Comment by BlythMeister** [comment]
This doesn't seem relevant to this watch face.
