### ISSUE TITLE
Fitbit Versa Lite Update (today) removed colors from bottom line of data

### ISSUE THREAD

**Issue by BlondieGayMan** [BlythMeister/Fitbit-Overview-Face#65]
This is my favorite face.  In fact, I've tried others, but this one just provides the info I like to know at a glance.
BEST FACE EVER!  :)

Today, my FitBit Versa Lite didn't an update.

After the update, I noticed that the lovely colors along the bottom have gone all white  as well, it appears that some of the text, like for the heart rate and date have gone a darker grey.

Perhaps the Dev is already aware of this and hopefully, working on an update to overcome whatever the FitBit devs did that changed things.

For troubleshooting, I did the usual things, of course.
-  hard rebooted the watch
-  uninstalled this face, installed a different one, then installed this one again.  No change!  Colors still all white along the bottom.

Hope this helps in resolving this issue.

**Comment by BlythMeister** [comment]
This was due to settings being reset by the Fitbit update.
Resetting the colours in settings will solve the issue.
