### ISSUE TITLE
Add battery to "stats"

### ISSUE THREAD

**Issue by Syhnd** [BlythMeister/Fitbit-Overview-Face#68]
Hi,
Thanks for your awesome work. 

I'd like to know if you could add a battery option alongside other options (distance, steps, burned calories). I don't like the look of the battery bar on top. 

Best regards

**Comment by BlythMeister** [comment]
Battery has a progress bar already along the top of the watch face?

In theory, adding as an option at the bottom stats section would also be possible, but things like colour would need to match those chosen for the top bar, meaning the progress bar could change colour as it drops.
